//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Concerto.rc
//
#define IDC_PRINT_IDENT                 2
#define IDD_COMB                        3
#define IDC_TEAMVIEWER                  3
#define IDC_VALID                       4
#define IDD_CONCERT_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_NUM                         139
#define IDI_ICON2                       150
#define IDD_IDENT                       161
#define IDB_RADIOV                      162
#define IDD_PRINTMESSAGE                163
#define IDD_MESSAGE                     164
#define IDD_GALERIE                     165
#define IDD_SIMPRINT                    166
#define IDB_RADIOR                      167
#define IDB_RADIO                       168
#define IDB_RADIOC                      169
#define IDB_RADIORED                    170
#define IDB_RADIOVERT                   171
#define IDB_QRVIEWSCAN                  172
#define IDB_RESEAU                      173
#define IDB_SERVEUR                     175
#define IDB_SERVEUR1                    176
#define IDB_SAUTO                       176
#define IDB_QRPHONE                     177
#define IDB_SCANBLUE                    178
#define IDB_SCANUSB                     179
#define IDB_GATE                        180
#define IDB_WEB                         181
#define IDI_CHECK                       194
#define IDI_NCHECK                      195
#define IDC_ART1                        1001
#define IDC_ART2                        1002
#define IDC_ART3                        1003
#define IDC_ART4                        1004
#define IDC_ART5                        1005
#define IDC_ART6                        1006
#define IDC_ART7                        1007
#define IDC_ART8                        1008
#define IDC_ART9                        1009
#define IDC_ART10                       1010
#define IDC_ART11                       1011
#define IDC_ART12                       1012
#define IDC_ART13                       1013
#define IDC_ART14                       1014
#define IDC_ART15                       1015
#define IDC_ART16                       1016
#define IDC_FIG                         1017
#define IDC_QUIT                        1018
#define IDC_FID                         1019
#define IDC_LIBEL1                      1020
#define IDC_LIBEL2                      1021
#define IDC_TOTAL                       1022
#define IDC_CA                          1023
#define IDC_NTA                         1024
#define IDC_NTT                         1025
#define IDC_MANAGER                     1026
#define IDC_LIBELCONS                   1027
#define IDC_QUITTER                     1028
#define IDC_CONFIG                      1029
#define IDC_BUREAU                      1030
#define IDC_IMPORT                      1031
#define IDC_PRINTER                     1032
#define IDC_BILPRINT                    1033
#define IDC_RAZ                         1034
#define IDC_COLOR                       1035
#define IDC_NET                         1035
#define IDC_NTOTAL                      1036
#define IDC_CASH_VIEW                   1037
#define IDC_CASH_CLOSE                  1038
#define IDC_RETURN                      1039
#define IDC_0                           1040
#define IDC_1                           1041
#define IDC_2                           1042
#define IDC_3                           1043
#define IDC_4                           1044
#define IDC_5                           1045
#define IDC_6                           1046
#define IDC_7                           1047
#define IDC_8                           1048
#define IDC_9                           1049
#define IDC_10                          1050
#define IDC_11                          1051
#define IDC_12                          1052
#define IDC_13                          1053
#define IDC_DEL                         1053
#define IDC_NCONSO                      1054
#define IDC_QTE                         1056
#define IDC_NSPECT                      1057
#define IDC_PTOT                        1058
#define IDC_LNTICK                      1059
#define IDC_CODE                        1060
#define IDC_LIBELSPECT                  1061
#define IDC_LPRIX                       1063
#define IDC_LCANCEL                     1065
#define IDC_NLIBEL1                     1066
#define IDC_LDATE                       1067
#define IDC_SPOSTE                      1068
#define IDC_NPAGE                       1069
#define IDC_NDATE                       1070
#define IDC_BILCANCEL                   1071
#define IDC_NPRIX                       1072
#define IDC_PRIX                        1073
#define IDC_RESULT                      1074
#define IDC_ARTICLE                     1075
#define IDC_NPOSTE                      1076
#define IDC_SNOM                        1077
#define IDC_NNOM                        1078
#define IDC_DA                          1079
#define IDC_SAD1                        1080
#define IDC_NCONS                       1081
#define IDC_NSERVEUR                    1082
#define IDC_NTVA1                       1083
#define IDC_VAL1                        1084
#define IDC_NAD1                        1085
#define IDC_SAD2                        1086
#define IDC_NAD2                        1087
#define IDC_BMANAGER                    1088
#define IDC_LOGO                        1089
#define IDC_CONTROL                     1090
#define IDC_NDEVISE                     1091
#define IDC_SSIRET                      1092
#define IDC_NSIRET                      1093
#define IDC_NMENTIONP                   1094
#define IDC_SMENTIONT                   1095
#define IDC_LIBELGUICHET                1096
#define IDC_SEARCH                      1097
#define IDC_VERSION                     1098
#define IDC_SMOIS                       1099
#define IDC_DIRLIST                     1100
#define IDC_ENT3                        1101
#define IDC_NLICENSE                    1102
#define IDC_SCONS                       1103
#define IDC_SNA                         1104
#define IDC_SNAF                        1104
#define IDC_ENT1                        1105
#define IDC_SELSPECT                    1106
#define IDC_NMENTIONT                   1107
#define IDC_ENT4                        1108
#define IDC_ENT2                        1109
#define IDC_NMOIS                       1110
#define IDC_NPAUTO                      1111
#define IDC_NNAUTO                      1112
#define IDC_NAN                         1113
#define IDC_SAN                         1114
#define IDC_ANNULER                     1115
#define IDC_SSERVEUR                    1115
#define IDC_AUTOPRINT                   1116
#define IDC_NPREFIX                     1116
#define IDC_AUTONEWS                    1117
#define IDC_SPREFIX                     1117
#define IDC_ENTRYMODE                   1118
#define IDC_LMAC                        1119
#define IDC_DUM                         1120
#define IDC_LNEWART                     1121
#define IDC_BUSER                       1122
#define IDC_LCOL                        1123
#define IDC_NLANGUE                     1123
#define IDC_GLOG                        1124
#define IDC_GCLIENT                     1125
#define IDC_GSECUR                      1126
#define IDC_GEDIT                       1127
#define IDC_NLIBEL                      1128
#define IDC_VALMASTER                   1129
#define IDC_LMAC2                       1129
#define IDC_LFILE                       1129
#define IDC_LTCONTROL                   1129
#define IDC_LTYPE                       1130
#define IDC_NVALPLACE                   1131
#define IDC_NNAF                        1132
#define IDC_VALPLACE                    1133
#define IDC_NVALPWD                     1134
#define IDC_HORAIRE                     1135
#define IDC_NVALCONTROL                 1136
#define IDC_NETC                        1137
#define IDC_VALMIX                      1138
#define IDC_NVALMIX                     1139
#define IDC_PSEND                       1140
#define IDC_TEMCONTROL                  1141
#define IDC_TEMNET                      1142
#define IDC_SOURCELIST                  1143
#define IDC_VALACTIF                    1144
#define IDC_VIM                         1145
#define IDC_TEMGATE                     1145
#define IDC_NVHORAIRE                   1146
#define IDC_VMCI                        1146
#define IDC_SOURCEDIRLIST               1147
#define IDC_SOURCEDATA                  1148
#define IDC_NPAYS                       1149
#define IDC_SDL                         1150
#define IDC_LTMP                        1151
#define IDC_VALENTRY                    1152
#define IDC_TVA1                        1153
#define IDC_TVA2                        1154
#define IDC_PAGE                        1155
#define IDC_NSCAN                       1156
#define IDC_LCUR                        1157
#define IDC_TEMWEB                      1157
#define IDC_LDEVISE                     1158
#define IDC_SDEVISE                     1159
#define IDC_SLICENSE0                   1160
#define IDC_SLICENSE1                   1161
#define IDC_SLICENSE2                   1162
#define IDC_SLICENSE3                   1163
#define IDC_SLICENSE4                   1164
#define IDC_SLICENSE5                   1165
#define IDC_SLICENSE6                   1166
#define IDC_SMES1                       1167
#define IDC_LCB                         1167
#define IDC_SMES2                       1168
#define IDC_LCB2                        1168
#define IDC_SMES3                       1169
#define IDC_SMES4                       1170
#define IDC_STITRE                      1171
#define IDC_SNUM                        1172
#define IDC_SNMES2                      1173
#define IDC_SNMES3                      1174
#define IDC_SMESSAGE                    1175
#define IDC_SNMES4                      1176
#define IDC_CHECK1                      1177
#define IDC_PIMP                        1178
#define IDC_LNBAP                       1179
#define IDC_PRICELIST                   1180
#define IDC_NEXER                       1181
#define IDC_SEXER                       1182
#define IDC_REPONSE                     1183
#define IDC_VALEXO                      1184
#define IDC_AUTEUR                      1185
#define IDC_VALEXO2                     1185
#define IDC_VALPASS                     1185
#define IDC_VAL2                        1186
#define IDC_LIM                         1187
#define IDC_VALCB                       1187
#define IDC_VALCBX                      1187
#define IDC_NVALPAGE                    1188
#define IDC_SPIN1                       1189
#define IDC_SERIAL                      1190
#define IDC_NTVA2                       1191
#define IDC_LTVA                        1192
#define IDC_LLANGUE                     1193
#define IDC_SLANGUE                     1194
#define IDC_LMOIS                       1195
#define IDC_LPAYS                       1196
#define IDC_SPAYS                       1197
#define IDC_MOTIF                       1198
#define IDC_SMENTIONP                   1199
#define IDC_SNMES1                      1200
#define IDC_CAL                         1201
#define IDC_TARGETLIST                  1202
#define IDC_SDUM                        1203
#define IDC_NF525                       1204
#define IDC_AVERT1                      1205
#define IDC_AVERT2                      1206
#define IDC_AVERT3                      1207
#define IDC_FAM1                        1208
#define IDC_FAM2                        1209
#define IDC_FAM3                        1210
#define IDC_RUB1                        1211
#define IDC_RUB2                        1212
#define IDC_RUB3                        1213
#define IDC_QR                          1214
#define IDC_TQR                         1215
#define IDC_PLUS                        1216
#define IDC_MOINS                       1217
#define IDC_GARB                        1218
#define IDC_QR2                         1219
#define IDC_QRPHONE                     1219
#define IDC_COPY                        1220
#define IDC_PASTE                       1221

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1220
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
